### ISSUE TITLE
Segfault on newer GCC versions

### ISSUE THREAD

**Issue by tsahyt** [alviano/wasp#4]
WASP produces a segfault when compiled with GCC 5.3.1 (on Fedora 23). This has been tested using graph coloring instances from ASPCOMP 2014, but it also fails most of the tests included with WASP.

The bug occurs when WASP is compiled with -O2 and above, but not with -O1. Compiling with `-fno-strict-aliasing` and `-fsanitize=undefined` sheds some light on the issue. As far as I understand, the call to `memcpy` in `src/stl/Vector.h:83` is given a null pointer at some point. GCC assumes (in accordance to the standard, see C11 standard §7.1.4), that this function must never be passed a null pointer and optimizes the checks away at high enough optimization levels, eventually resulting in a segfault.

Some research suggests that the bug might occur with any GCC version > 4.9. See [the porting guide for 4.9](https://gcc.gnu.org/gcc-4.9/porting_to.html), in particular the section "Null pointer checks may be optimized away more aggressively". Indeed, the code does work on GCC 4.8.4.

I've attached an instance from ASPCOMP 2014 which produces the error for me.

[graphcol.txt](https://github.com/alviano/wasp/files/208159/graphcol.txt)

**Comment by dodaro** [comment]
Thank you for pointing this out. Now, the problem should be fixed.
