### ISSUE TITLE
Cant get WASP to work with a grounder

### ISSUE THREAD

**Issue by bowesdorp** [alviano/wasp#5]
Hi,

When I try to use WASP with a grounder (gringo or idlv) it does not seem to work. It says that the output provided by the grounders is "unsupported rule type". I hope someone could help me fix this issue.

Sincerely,

Bo

**Comment by alviano** [comment]
Hi!

May you provide us an example of input and the command line you use? Also
the version of gringo will help.

Thank you!

All the best,
m

**Comment by alviano** [comment]
And maybe try to add

--output=smodels

to the command-line of gringo and idlv.

m

**Comment by bowesdorp** [comment]
So when i use idlv, i use : $ ./dlv.x86-64-linux-elf-static.bin
~/Desktop/test.lp | ~/Desktop/alviano-wasp-2c1bda3/build/release/wasp
and with gringo: $ gringo ~Destop/test.lp |
~/Desktop/alviano-wasp-2c1bda3/build/release/wasp
My version of gringo is 5.3.0



Op ma 27 mei 2019 om 10:07 schreef Mario Alviano <notifications@github.com>:

> And maybe try to add
>
> --output=smodels
>
> to the command-line of gringo and idlv.
>
> m
>
>

**Comment by dodaro** [comment]
Hi Bo,

try
gringo ~/Desktop/test.lp --output=smodels |
~/Desktop/alviano-wasp-2c1bda3/build/release/wasp

Concerning dlv.x86-64-linux-elf-static.bin, it seems a binary of DLV, whose output is not parsable by wasp. Note that i-DLV is available here: https://github.com/DeMaCS-UNICAL/I-DLV/releases

Best,
Carmine

**Comment by bowesdorp** [comment]
thanks, that fixed the problem.

I have another question, is there a way to store the statistics of the
solver locally?

Sincerely,
Bo

Op ma 27 mei 2019 om 10:20 schreef dodaro <notifications@github.com>:

**Comment by dodaro** [comment]
The only way is to use the option --stats and redirect the standard error to a file:

gringo ~/Desktop/test.lp --output=smodels |
~/Desktop/alviano-wasp-2c1bda3/build/release/wasp --stats=2 2> yourfile.txt
