### ISSUE TITLE
Can't set up the python API

### ISSUE THREAD

**Issue by mourad-hassani** [alviano/wasp#6]
Is there a tutorial on how to use the python API of Wasp ?

**Comment by dodaro** [comment]
To use the python API of wasp you should compile wasp with python:
`make SCRIPT=python` (for python 2.7)
`make SCRIPT=python3` (for python <= 3.7)
`make SCRIPT=python38` (for python >= 3.8)

A preliminary documentation is here: http://alviano.github.io/wasp/plugins-documentation.html.
