### ISSUE TITLE
Executing Wasp in stream reasoning mode

### ISSUE THREAD

**Issue by mourad-hassani** [alviano/wasp#7]
Hi,

The code available at http://distributed-stream-reasoner.ainf.at/reconf/ (which is very similar to the branch "streamreasoning" in this repo) is not working. Is there a working implementation of the paper: "Managing caching strategies for stream reasoning with reinforcement learning" ? Is there a way to execute Wasp for stream reasoning?

Thank you.

**Comment by dodaro** [comment]
Hi, stream reasoning is handled as a separate project and I am not the maintainer of that repository. Please send an email to me and all the co-authors of the paper so that other colleagues can help you.

Best,
Carmine

**Comment by mourad-hassani** [comment]
Thank you.
