### ISSUE TITLE
Compute **anytime** cautious reasoning

### ISSUE THREAD

**Issue by mahi045** [alviano/wasp#8]
I am using wasp to compute cautious reasoning.
What is the command to compute _anytime_ cautious reasoning using wasp? Is it enough to use the params ``--minimization-cautious-enum`` or ``--minimization-cautious`` with ``./wasp`` command?

Thanks in advance.

**Comment by dodaro** [comment]
Hi, the option to compute cautious consequences is `--query-algorithm=alg` where alg is one of ict, or, cb, chunk-static, chunk-dynamic, preferences, one, kdyn, pmres, pi, or ict-preferences.

If you want anytime answers, my suggestion is to start with `--query-algorithm=ict` and `--query-verbosity=1` (which enables the print of certain answers produced during the computation).
