### ISSUE TITLE
Time-Limited Enumeration of Answer Sets

### ISSUE THREAD

**Issue by mahi045** [alviano/wasp#9]
Hi,
Is there a feature in WASP that allows for the enumeration of answer sets within a specified time frame? Additionally, can it display the count of answer sets that have been enumerated during that period?

Thanks in advance

**Comment by dodaro** [comment]
Hi,

You can use the options "-n0 --silent=2" to enumerate all answer sets and to obtain a cumulative number of enumerated answer sets.

Output: `Number of printed answers: 2`

However, in its current implementation, wasp does not support an early termination after a given timeout. You should use an external tool, e.g. pyrunlim (https://github.com/alviano/python/tree/master/pyrunlim) or dumbo-runlim (https://github.com/alviano/dumbo-runlim).

**Comment by mahi045** [comment]
@dodaro Thanks for your answer. 
I have another question: Can we do projected enumeration in WASP?

**Comment by dodaro** [comment]
You are welcome!

No, this feature is not supported.
